### PR TITLE
stage-2

### PR DESCRIPTION
**Pull request by larkceresin**
Initial stage 2 submission

### CODE REVIEW

**Comment by ImaliaNsk** [comment]
Hello Jenna!
Good job! Some corrections need to be made, but on the whole, the project looks quite good. However, I couldn't check the layout of search results and sevaed news, please add some cards or let me know how to get to the search results.

# Project review summary:
### Performance Criteria
- [ ]  The project is adapted for different screen resolutions and matches the designs for these resolutions. There is no horizontal scrolling on resolutions of 320px and up. The scrollbar can't be hidden using the overflow: hidden declaration.
There's a horizontall scroll: http://joxi.ru/8AnK1e1UywByKr It's necessary to find all properties which cause scrolling on desktop resolutions.
Some other mismatches with the design:
- http://joxi.ru/nAyyl4luw4OwqA (it's necessary to correct all similar cases, some other elements have incorrect font-family too)
- The layout in "about" section doesn't correspond to the design: image should have a bigger top margin than the heading, please check the design.
- The "Home" button is located incorrectly and has incorrect fon-size, please check the design. Please check how the menu items are located on all pages, the menu should match the design: http://joxi.ru/BA0xqPqHpd0qPA
- The "Sign in" button should have a white border.
- Some elements have incorrect font-weight because of incorrectly linked fonts, please check: http://joxi.ru/YmEwlxlCMvnBEA - should be normal font-weight, but the needed font isn't connected
- the button closing popups should have a transparent background: http://joxi.ru/l2ZwzOzC7B6lZA
- the background color of the menu shouldn't be black: http://joxi.ru/eAOw8Q8CkdyDxA
- the background image in the header doesn't correspond to the design on 320 viewport.
- [ ]  All the blocks from the brief have been coded. Navigation between pages and links to external resources are working correctly: there are no broken links or links leading to an anchor on the page and external links open in a new tab.
Please let me know how I can check the layout of the page with search, search results and saved articles. It's necessary to add some cards to check the layout.
- [ ]  The layout is responsive and displays correctly at all intermediate resolutions.
Some content is displayed incorrectly on intermediate resolutions: http://joxi.ru/p27JpQpHN9QDdm. Please correct all the similar issues. I haven't been able to check the cards layout on media screens, please add some cards or let me know how I can check it.
- [ ]  There are no validation errors.
http://joxi.ru/52awW7WCkN6y4r Please find and correct all similar issues
- [x]  Semantic HTML is used, meaning that semantic tags are used. All elements are used correctly (e.g. a paragraph must be a paragraph, a list must be a list). The DOM tree structure doesn't consist only of <div> containers.
- [x]  The correct approach is chosen for positioning elements, and is described using the correct syntax. For example, when positioning an element absolutely, its parent block is relatively positioned.
- [x]  flex or grid  layout are used to arrange elements.
- [x]  Infrastructural project files are created using CRA.
- [x]  The popup windows have opening and closing functionality implemented.
- The markup has been converted into JSX:
	- [x]  The markup is included within parentheses ( ).
	- [x]  The markup has been moved into the corresponding components.
- Your project contains:
	- [x]  An images folder
	- [x]  A components folder with JS and CSS files for the components.
	- [x]  A fonts folder.
	
### Best Practices
- [x]  Classes are named according to BEM specifications. 
- [ ]  Buttons, input fields, and links are implemented in all of the states specified in the design.
Please add cursor: pointer to the buttons.
I'd recommend to remove outline from buttons when they are focused: http://joxi.ru/DmB9KOKs4vXobr
- [x]  The design reuses components wherever possible.
- [x]  Fonts are connected using @font-face.
- [x]  The use of reset.css is prohibited.
- [x]  Form elements should be highlighted when focused.
- [x]  The form must have placeholders, and required fields should be validated.

### Recommendations
- [x]  Images have an alt attribute containing appropriate values.
- [x]  System fonts are connected as alternatives to each of your fonts.
- [x]  Raster and vector images have been optimized.

## Number of points: 52

## Additional comments:
besides the criteria listed above, I'd suggest to fix the following issue to match the design better:
- on media screens, different sectiona have different content width (e.g. http://joxi.ru/KAgwR4RCKYR7jA). Please, correct in other similar cases too.

**Comment by larkceresin** [comment]
Made temp cards for display purposes.
App.js has sections commented out for results/ no results/ and preloader. Can remove comments on each one to check them out.

**Comment by ImaliaNsk** [comment]
Thanks for fixes and for template cards! However, there are still some issues to work on before the project can be accepted. Most issues are about matching the design, currently the project has a lot of mismatches.

# Project review summary:
### Performance Criteria
- [ ]  The project is adapted for different screen resolutions and matches the designs for these resolutions. There is no horizontal scrolling on resolutions of 320px and up. The scrollbar can't be hidden using the overflow: hidden declaration.
Some mismatches with the design:
- the card design doesn't correspond to the mockup: http://joxi.ru/E2pa747TGeGaDA. Also, the trash can icon should have a message "Remove from saved" when being hovered over
- the background image is losing its proportions: http://joxi.ru/DmB9KOKs4B4ggr. According to the design, on mobile screens another picture should be used as a background.
- the search form input has Times New Roman font
- shouldn't have borders and also should appear only when the bookmark is being hovered over: http://joxi.ru/L21kgPgh0q0Ozr
- http://joxi.ru/YmEwlxlCM6MjPA
- the button shouldn't have a black border http://joxi.ru/nAyyl4luwNwvYA
- [x]  All the blocks from the brief have been coded. Navigation between pages and links to external resources are working correctly: there are no broken links or links leading to an anchor on the page and external links open in a new tab.
- [ ]  The layout is responsive and displays correctly at all intermediate resolutions.
the button is incorrectly located: http://joxi.ru/krDvaXaT454BR2
the images in cards lose their proportions on intermediate resolutions: http://joxi.ru/823yGPGu8q8gyr
the content isn't centered on some resolutions: http://joxi.ru/n2Ywp3pCepepRr
- [ ]  There are no validation errors.
http://joxi.ru/bmoly4yUy0ylX2
http://joxi.ru/l2ZwzOzC7Z734A Please find and correct all similar issues
- [x]  Semantic HTML is used, meaning that semantic tags are used. All elements are used correctly (e.g. a paragraph must be a paragraph, a list must be a list). The DOM tree structure doesn't consist only of <div> containers.
- [x]  The correct approach is chosen for positioning elements, and is described using the correct syntax. For example, when positioning an element absolutely, its parent block is relatively positioned.
- [x]  flex or grid layout are used to arrange elements.
- [x]  Infrastructural project files are created using CRA.
- [x]  The popup windows have opening and closing functionality implemented.
- The markup has been converted into JSX:
	- [x]  The markup is included within parentheses ( ).
	- [x]  The markup has been moved into the corresponding components.
- Your project contains:
	- [x]  An images folder
	- [x]  A components folder with JS and CSS files for the components.
	- [x]  A fonts folder.
	
### Best Practices
- [x]  Classes are named according to BEM specifications. 
- [ ]  Buttons, input fields, and links are implemented in all of the states specified in the design.
The bookmark should become blue on click: http://joxi.ru/KAx1040uKLKb1r
- [x]  The design reuses components wherever possible.
- [x]  Fonts are connected using @font-face.
- [x]  The use of reset.css is prohibited.
- [x]  Form elements should be highlighted when focused.
- [x]  The form must have placeholders, and required fields should be validated.

### Recommendations
- [x]  Images have an alt attribute containing appropriate values.
- [x]  System fonts are connected as alternatives to each of your fonts.
- [x]  Raster and vector images have been optimized.

## Number of points: 66

**Comment by ImaliaNsk** [comment]
Congratulations, the project is accepted!

# Project review summary:
### Performance Criteria
- [x]  The project is adapted for different screen resolutions and matches the designs for these resolutions. There is no horizontal scrolling on resolutions of 320px and up. The scrollbar can't be hidden using the overflow: hidden declaration.
Some other mismatches with the design:
- **the boorkmark button shouldn't be outlined**
- [x]  All the blocks from the brief have been coded. Navigation between pages and links to external resources are working correctly: there are no broken links or links leading to an anchor on the page and external links open in a new tab.
- [ ]  The layout is responsive and displays correctly at all intermediate resolutions.
the content isn't centered on some resolutions: http://joxi.ru/1A58EPECbEZ872
- [x]  There are no validation errors.
- [x]  Semantic HTML is used, meaning that semantic tags are used. All elements are used correctly (e.g. a paragraph must be a paragraph, a list must be a list). The DOM tree structure doesn't consist only of <div> containers.
- [x]  The correct approach is chosen for positioning elements, and is described using the correct syntax. For example, when positioning an element absolutely, its parent block is relatively positioned.
- [x]  flex or grid layout are used to arrange elements.
- [x]  Infrastructural project files are created using CRA.
- [x]  The popup windows have opening and closing functionality implemented.
- The markup has been converted into JSX:
	- [x]  The markup is included within parentheses ( ).
	- [x]  The markup has been moved into the corresponding components.
- Your project contains:
	- [x]  An images folder
	- [x]  A components folder with JS and CSS files for the components.
	- [x]  A fonts folder.
	
### Best Practices
- [x]  Classes are named according to BEM specifications. 
- [x]  Buttons, input fields, and links are implemented in all of the states specified in the design.
- [x]  The design reuses components wherever possible.
- [x]  Fonts are connected using @font-face.
- [x]  The use of reset.css is prohibited.
- [x]  Form elements should be highlighted when focused.
- [x]  The form must have placeholders, and required fields should be validated.

### Recommendations
- [x]  Images have an alt attribute containing appropriate values.
- [x]  System fonts are connected as alternatives to each of your fonts.
- [x]  Raster and vector images have been optimized.

## Number of points: 86

**Pull request merged**
